swagger: '2.0'
info:
  description: 'OpenAPI for Flink Monitoring REST API'
  version: 1.0.0
  title: Flink Monitoring REST API
  license:
    name: Apache-2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: localhost:8081
basePath: /v1
tags:
  - name: monitoring
    description: Flink Monitoring API
schemes:
  - http
paths:
  /jars:
    get:
      tags:
        - monitoring
      summary: Returns a list of all jars previously uploaded via '/jars/upload'.
      description: ''
      operationId: getJars
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: urn:jsonschema:org:apache:flink:runtime:webmonitor:handlers:JarListInfo
          required: true
          schema:
            $ref: '#/definitions/JarListInfo'
      responses:
        '200':
          description: Sucessful operation
  /config:
    get:
      tags:
        - monitoring
      summary: Returns the configuration of the WebUI.
      description: ''
      operationId: getConfig
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: urn:jsonschema:org:apache:flink:runtime:rest:messages:DashboardConfiguration
          required: true
          schema:
            $ref: '#/definitions/DashboardConfiguration'
      responses:
        '200':
          description: Sucessful operation
  /jars/upload:
    post:
      tags:
        - monitoring
      summary: Uploads a jar to the cluster. 
      description: ''
      operationId: uploadJar
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: additionalMetadata
          in: formData
          description: Additional data to pass to server
          required: false
          type: string
        - name: file
          in: formData
          description: file to upload
          required: false
          type: file
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/ApiResponse'
definitions:
  JarListInfo:
    title: Jar list info
    type: object
    properties:
      address:
        type: string
      files:
        type: array
        items:
          type: object
          id: urn:jsonschema:org:apache:flink:runtime:webmonitor:handlers:JarListInfo:JarFileInfo
          properties:
            id:
              type: string
            name:
              type: string
            uploaded:
              type: integer
            entry:
              type: array
              items:
                type: object
                id: urn:jsonschema:org:apache:flink:runtime:webmonitor:handlers:JarListInfo:JarEntryInfo
                properties:
                  name:
                    type: string
                  description:
                    type: string                
  DashboardConfiguration:
    type: object
    id: urn:jsonschema:org:apache:flink:runtime:rest:messages:DashboardConfiguration
    properties:
      refresh-interval:
        type: integer
      timezone-name:
        type: string
      timezone-offset:
        type: integer
      flink-version:
        type: string
      flink-revision:
        type: string
  ApiResponse:
    title: An uploaded response
    description: Describes the result of uploading an image resource
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string