/**
 * Flink Monitoring REST API
 * OpenAPI for Flink Monitoring REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class JarRunRequestBody (
  entryClass: Option[String] = None,
  programArgs: Option[String] = None,
  programArgsList: Option[Seq[String]] = None,
  parallelism: Option[Int] = None,
  jobId: Option[String] = None,
  allowNonRestoredState: Option[Boolean] = None,
  savepointPath: Option[String] = None
) extends ApiModel


