/**
 * Flink Monitoring REST API
 * OpenAPI for Flink Monitoring REST API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.client.model

import org.openapitools.client.core.ApiModel
import org.joda.time.DateTime
import java.util.UUID

case class JobVertexDetailsInfo (
  id: String,
  name: String,
  parallelism: Int,
  status: JobVertexDetailsInfoEnums.Status,
  startTime: Option[Int] = None,
  endTime: Option[Int] = None,
  duration: Option[Int] = None,
  tasks: Map[String, Int],
  metrics: IOMetricsInfo
) extends ApiModel

object JobVertexDetailsInfoEnums {

  type Status = Status.Value
  object Status extends Enumeration {
    val CREATED = Value("CREATED")
    val SCHEDULED = Value("SCHEDULED")
    val DEPLOYING = Value("DEPLOYING")
    val RUNNING = Value("RUNNING")
    val FINISHED = Value("FINISHED")
    val CANCELING = Value("CANCELING")
    val CANCELED = Value("CANCELED")
    val FAILED = Value("FAILED")
    val RECONCILING = Value("RECONCILING")
  }

}

